// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package exception

import (
	"myapp/api/exception"
)

type ControllerV1 struct{}

func NewV1() exception.IExceptionV1 {
	return &ControllerV1{}
}
